### PR TITLE
Add `table.sort`

### PR DESCRIPTION
**Pull request by RiskoZS**
Behaves identically to the standard function, but also returns the sorted table (can work as a drop-in replacement). I find this functionality immensely useful in my projects.

### CODE REVIEW

**Comment by Bilal2453** [comment]
May I ask for an example where this is useful? Wouldn't it be that if you are sorting a table, you already have a reference to it?

**Comment by RiskoZS** [comment]
Say for example you want to sort a table and then perform some other function on it, like `table.slice`:
```lua
table.sort(scores)
local topThree = table.slice(scores, 1, 3)

-- vs

local topThree = table.slice(table.sort(scores), 1, 3)
```
Or, for example, if sorting a table is the last step in some function, with this you'd be able to just `return table.sort(tbl)` instead of having to sort and return it on two separate lines:
```lua
local function sortedKeys(tbl)
    local keys = table.keys(tbl)
    table.sort(keys)
    return keys
end

-- vs

local function sortedKeys(tbl)
    return table.sort(table.keys(tbl))
end
```

**Comment by RiskoZS** [comment]
Now that I'm thinking about it, it may also be a good idea to have `table.shift` return the input table as well, for the same reasons as mentioned above. It'll also be more consistent since most of the in-place functions (`table.join`, `table.merge`, etc.) already return the input table even though they don't strictly have to.

**Comment by truemedian** [comment]
I do not believe that overriding standard library functions with non-compliant forms is a good idea.

**Pull request closed without merging**
